/// Flutter icons UI2
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  UI2
///      fonts:
///       - asset: fonts/UI2.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class UI2 {
  UI2._();

  static const _kFontFam = 'UI2';
  static const String? _kFontPkg = null;

  static const IconData instagram = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paint_board_and_brush = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData register = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData searching_a_person = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData setting = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData timetable = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tru_logo = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData viewpassword = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData about = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checklist = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_chevron = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData finance = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData friends = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData git_hub = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
