/// Flutter icons UnivolveIcons2
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  UnivolveIcons2
///      fonts:
///       - asset: fonts/UnivolveIcons2.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class UnivolveIcons2 {
  UnivolveIcons2._();

  static const _kFontFam = 'UnivolveIcons2';
  static const String? _kFontPkg = null;

  static const IconData screenshot_2024_03_20_at_4_56_46_pm = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
