/// Flutter icons Univolve2
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Univolve2
///      fonts:
///       - asset: fonts/Univolve2.ttf
///
/// 
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
///
import 'package:flutter/widgets.dart';

class Univolve2 {
  Univolve2._();

  static const _kFontFam = 'Univolve2';
  static const String? _kFontPkg = null;

  static const IconData th_large = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData events = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData about = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checklist = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_chevron = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData friends = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification_1 = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_1 = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData searching_a_person = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tru_logo = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paint_board_and_brush = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData register = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData viewpassword = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData screenshot_2024_03_20_at_4_56_46_pm = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData accounting = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_clock = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qr_code = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData setting__2_ = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData manu = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
